apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cronjob
  namespace: monitoring  # Specify the namespace
spec:
  schedule: "*/5 * * * *"  # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: example-job
            image: busybox
            args:
            - /bin/sh
            - -c
            - "echo Hello, Kubernetes! && date"
          restartPolicy: OnFailure